### ISSUE TITLE
Error at provisioning

### ISSUE THREAD

**Issue by th3m4ri0** [chad-thompson/vagrantpress#78]
> ==> default: Debug: Executing '/usr/bin/pear update-channels'
> ==> default: Notice: /Stage[main]/Php5::Install/Exec[pear update-channels]/returns: executed successfully
> ==> default: Debug: /Stage[main]/Php5::Install/Exec[pear update-channels]: The container Class[Php5::Install] will propagate my refresh event
> ==> default: Debug: Exec[pear install PHP_CodeBrowser](provider=posix): Executing '/usr/bin/pear install --alldeps pear.phpunit.de/PHP_CodeBrowser'
> ==> default: Debug: Executing '/usr/bin/pear install --alldeps pear.phpunit.de/PHP_CodeBrowser'
> ==> default: Error: Command exceeded timeout
> ==> default: Debug: Exec[pear install phploc](provider=posix): Executing '/usr/bin/pear install --alldeps pear.phpunit.de/phploc'
> ==> default: Debug: Executing '/usr/bin/pear install --alldeps pear.phpunit.de/phploc'
> ==> default:
> ==> default: Error: /Stage[main]/Phpqa::Install/Exec[pear install PHP_CodeBrowser]/returns: change from notrun to 0 failed: Command exceeded timeout

**Comment by battlemidget** [comment]
obsolete as pear is deprecated
