### ISSUE TITLE
Provision local IP so :8080 is not required

### ISSUE THREAD

**Issue by gmisura** [chad-thompson/vagrantpress#83]
Using vip-quickstart as a model, provision a new local IP when the vagrant VM is created so port 80 can be used.

It does require mapping the IP to the VM
And adding an entry to hosts (on the host machine) 

But I think it is much cleaner to use http://vagrantpress.dev/ than to use http://localhost:8080/

**Comment by Johnstonian** [comment]
this is a good idea. would also help with possible port collisions s well.

**Comment by Johnstonian** [comment]
this issue can be closed. the feature was added with the latest merge. thanks to @gmisura for the suggestion!
