### ISSUE TITLE
PHPUnit and related tools no longer install via PEAR

### ISSUE THREAD

**Issue by kander** [chad-thompson/vagrantpress#86]
https://github.com/sebastianbergmann/phpunit/wiki/End-of-Life-for-PEAR-Installation-Method

Vagrant up yields errors, due to the PHP quality tools no longer being installable via PEAR; composer is now the recommended install mechanism.

**Comment by battlemidget** [comment]
Patches welcomed, if I find some time in the following weeks ill try to get this fixed

**Comment by kander** [comment]
Hi Adam; likewise I'm a bit strapped for time but I'll see if I can provide a patch. Would you prefer to build upon an existing Puppet module for composer, or do you want it KISS by just firing a bunch of exec's in sequence?

**Comment by battlemidget** [comment]
hey @kander through puppet would be preferable

thanks

**Comment by Johnstonian** [comment]
I removed PEAR and related tools in my fork which allows vagrantpress to spin up without errors for the time being: https://github.com/Johnstonian/vagrantpress. I plan to work on a patch that will install the PHP quality tools via composer. I can submit a pull request when done if welcomed.

**Comment by battlemidget** [comment]
@Johnstonian definitely, when ready create a PR and ill review it, thanks!

**Comment by Johnstonian** [comment]
this issue can probably be closed now.

**Comment by battlemidget** [comment]
Thanks!
