### ISSUE TITLE
home page mention outdated wordpress version

### ISSUE THREAD

**Issue by andreabedini** [chad-thompson/vagrantpress#96]
> WordPress v. 3.8 (With the git clone command, you’ll have access to all tagged releases of WordPress, but the puppet script currently creates a database appropriate for v. 3.8. Earlier versions have not been tested at this writing. See the roadmap sections for more detail about where the project is going.)

I'd send a PR but there's too much copy to change ;-)

**Comment by Johnstonian** [comment]
@andreabedini can you provide a little more detail? I'm not sure where you are finding this verbiage pasted into the issue comments.

**Comment by andreabedini** [comment]
@Johnstonian sorry, it's in the homepage https://github.com/chad-thompson/vagrantpress/blob/gh-pages/index.md#what-does-vagrantpress-install

**Comment by battlemidget** [comment]
We could probably just update gh-pages branch with the latest readme and close this out

**Comment by Johnstonian** [comment]
@battlemidget the README for on the gh-pages branch seems to be an auto-generated jekyll readme. Should we replace this with the master branch readme? Also, the doc @andreabedini references is the index.md. Should we update that to have the readme info from the master branch?

**Comment by battlemidget** [comment]
@Johnstonian yea I think thats a good idea just to keep them synced (not sure if there is an automated way to do that via github or if its just merging that file from master)

**Comment by Johnstonian** [comment]
pull request submitted: https://github.com/chad-thompson/vagrantpress/pull/97
