### ISSUE TITLE
The SSH command responded with a non-zero exit status.

### ISSUE THREAD

**Issue by reggi** [chad-thompson/vagrantpress#99]
Just got this error and the process exited.

```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by superpowered** [comment]
I'm also receiving this error with any new vagrant machines.
![screen shot 2015-06-04 at 2 27 25 pm](https://cloud.githubusercontent.com/assets/7035467/7992582/f3a37ee2-0ac5-11e5-9c3e-73e2e0b5660c.png)
![screen shot 2015-06-04 at 2 27 47 pm](https://cloud.githubusercontent.com/assets/7035467/7992586/f656e89a-0ac5-11e5-9d8a-d30213e9d49e.png)
![screen shot 2015-06-04 at 2 27 56 pm](https://cloud.githubusercontent.com/assets/7035467/7992588/fa4e037a-0ac5-11e5-84a0-68861b6bd266.png)
![screen shot 2015-06-04 at 2 28 07 pm](https://cloud.githubusercontent.com/assets/7035467/7992590/fd7f37ee-0ac5-11e5-9c50-762cdd1f350b.png)
![screen shot 2015-06-04 at 2 28 15 pm](https://cloud.githubusercontent.com/assets/7035467/7992593/00af69a2-0ac6-11e5-9f23-63efc6045242.png)

**Comment by joearcher** [comment]
Bump. I get this as well.

**Comment by gniewomir** [comment]
I got it also, at the end of provisioning process, but whole VM seems to be doing fine anyway,

**Comment by superpowered** [comment]
I've been getting this for the last month or so. 

Also, in addition to this error, sometimes I have to destroy and rebuild the machine multiple times before it works. After the initial setup hurdle the box seems to work just fine, however.
I've tried halting and then running vagrant up to save time, but then it just gets stuck in a remote disconnect loop.

**Comment by rap** [comment]
I've been having this problem too — here's my fix, in the hopes that it helps someone else.

When I inspected the verbose output from `vagrant up`, I noticed that errors during installation were always preceded by this message:

> The following exception is caused by a lack of memory and not having swap configured
> Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

The note at that URL indicates that Composer (which Vagrant appears to be using to pull in extra PHP libraries for Wordpress) fails in this manner when it's out of RAM. So I modified the project's Vagrantfile like so:

    config.vm.provider :virtualbox do |vb|
        # Add the following line if Composer is running out of RAM
        vb.memory = 2048
        vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
        vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
    end

Worked on the first try. You may be able to adjust this line to reduce the amount of memory you're allocating to Vagrant, if your system isn't long on available RAM.

(Fair warning that I know absolutely nothing about Vagrantpress, Composer, or Vagrant other than what I've learned trying to set up this project, so I don't have any further insight other than what I've noted here!)

**Comment by battlemidget** [comment]
@rap your comment is a good candidate for the wiki, maybe under "Troubleshooting Tips" or similar

**Comment by rap** [comment]
@battlemidget That's a good idea — adding it now.

**Comment by battlemidget** [comment]
Thanks!

https://github.com/chad-thompson/vagrantpress/wiki/Troubleshooting-tips

**Comment by battlemidget** [comment]
So I guess the question here is do we set a default minimum memory or just direct those to the wiki page if this problem occurs?

**Comment by axelson** [comment]
Can we add a link to the troubleshooting tips from the main README as well? I had no idea that it existed (many open source wiki's are blank).
